# Generated by Django 5.1.4 on 2024-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=40)),
                ('last_name', models.CharField(default=None, max_length=40)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('instrument_type', models.CharField(choices=[('cello', 'cello'), ('gitar', 'gitar'), ('flute', 'flute')], max_length=20)),
            ],
        ),
    ]
